# Generated by Django 5.0.6 on 2026-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubarr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="resolved_from",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="trackitem",
            name="manually_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trackitem",
            name="resolution_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackitem",
            name="resolution_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
