# Generated by Django 5.0.6 on 2026-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubarr", "0002_artist_resolved_from_trackitem_manually_edited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="last_sync_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="last_sync_summary",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="sync_task_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
