# Generated by Django 5.0.6 on 2026-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubarr', '0003_appsettings_last_sync_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackitem',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
