# Generated by Django 5.0.6 on 2026-09-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubarr', '0004_trackitem_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackitem',
            name='best_guess_mbid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='trackitem',
            name='best_guess_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
